name: bip32
description: A BIP32 compatible library for Flutter writing by Dart.
version: 1.0.0
homepage: https://github.com/anicdh
author: anicdh <anic.dh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.0-rc2
  hex: ^0.1.2
  bs58check: ^1.0.0
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
