name: bip32
description: A BIP32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) compatible library for Flutter writing by Dart.
version: 1.0.10
homepage: https://github.com/dart-bitcoin/bip32-dart
author: anicdh <anic.dh@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pointycastle: ^3.0.1
  hex: ^0.2.0
  bs58check: ^1.0.2

dev_dependencies:
  test: ^1.0.0
